CREATE TABLE stations (
	id INTEGER NOT NULL PRIMARY KEY, 
	docks INTEGER NOT NULL, 
	lat FLOAT NOT NULL, 
	long FLOAT NOT NULL, 
	name VARCHAR(45) NOT NULL
);

CREATE TABLE features (
	key SERIAL PRIMARY KEY , 
	date TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	id FLOAT NOT NULL, 
	bikes_out FLOAT NOT NULL, 
	bikes_in FLOAT NOT NULL, 
	weekday FLOAT NOT NULL, 
	hour FLOAT NOT NULL
);


